name: Pilot Request
about: Apply for one of the first 5 pilot slots (self-run)
labels: [pilot]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest. Pilot support is limited to 5 teams.
        If slots are full, we’ll reply with timing for the next wave.
  - type: input
    id: company
    attributes:
      label: Company / Team
      placeholder: Your team name
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact (email or handle)
      placeholder: you@company.com
    validations:
      required: true
  - type: dropdown
    id: agent_type
    attributes:
      label: Agent stack
      options:
        - Custom
        - LangChain / LangGraph
        - OpenAI Assistants / Responses
        - Anthropic Tools
        - CrewAI
        - Other
    validations:
      required: true
  - type: dropdown
    id: run_case
    attributes:
      label: Do you already expose /run-case?
      options:
        - Yes
        - No
        - Not sure
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: What’s your main use case?
      placeholder: Regression testing, safety checks, compliance evidence, etc.
    validations:
      required: true
